export const BLUE_MAP_RUNTIME = {
	HIRES_VIEW_DISTANCE: 100,
	FLAT_VIEW_DISTANCE: 1500,
	PERSPECTIVE_DEFAULT_DISTANCE: 1200,
	PERSPECTIVE_MIN_DISTANCE: 35,
	MODE_TRANSITION_MS: 520,
	PLAYER_MODEL_HIDDEN_DISTANCE: 460,
	PLAYER_MODEL_SWITCH_DISTANCE: 360,
	PLAYER_MODEL_SCALE: 0.65,
	PLAYER_VIEW_MAX_ANGLE: Math.PI / 5,
	PLAYER_MARKER_HEIGHT_OFFSET: 8,
	PLAYER_DIRECTION_LENGTH: 18,
} as const
